eureka:
    client:
        enabled: ${GATEWAY_EUREKA_CLIENT_ENABLED}
        initial-instance-info-replication-interval-seconds: 120
        instance-info-replication-interval-seconds: 120
        serviceUrl:
            defaultZone: http://${GATEWAY_EUREKA_HOST}:${GATEWAY_EUREKA_PORT}/eureka
            registerWithEureka: true
    instance:
        prefer-ip-address: true
info:
    app:
        description: '@project.description@'
        encoding: '@project.build.sourceEncoding@'
        java:
            version: '@java.version@'
        name: '@project.name@'
        version: '@project.version@'
logging:
    level:
        org:
            hibernate:
                SQL: INFO
                type:
                    descriptor:
                        sql:
                            BasicBinder: INFO
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: ${GATEWAY_SERVER_PORT}
spring:
    cloud:
        discovery:
            enabled: true
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            globalcors:
                corsConfigurations:
                    '''[/**]''':
                        allowedMethods: GET,POST,PUT,PATCH,DELETE
                        allowedOrigins: '*'
            metrics:
                enabled: true
            routes:
                - id: soldier-service
                  uri: lb://soldier-service
                  predicates:
                      - Path=/soldier/**
                  filters:
                      - name: CircuitBreaker
                        args:
                            fallbackUri: forward:/soldierServiceFallBack
                            name: soldier
                      - RewritePath=/soldier/(?<remaining>.*), /${remaining}
                - id: army-service
                  uri: lb://army-service
                  predicates:
                      - Path=/army/**
                  filters:
                      - name: CircuitBreaker
                        args:
                            fallbackUri: forward:/armyServiceFallBack
                            name: army
                      - RewritePath=/army/(?<remaining>.*), /${remaining}
        loadbalancer:
            ribbon:
                enabled: false
        service-registry:
            auto-registration:
                enabled: true
    main:
        web-application-type: reactive
    zipkin:
        baseUrl: http://${GATEWAY_ZIPKIN_HOST}:${GATEWAY_ZIPKIN_PORT}
        enabled: ${GATEWAY_ZIPKIN_CLIENT_ENABLED}
springdoc:
    swagger-ui:
        enabled: ${GATEWAY_SWAGGER_ENABLED}
