emp:
    soldier:
        description: '@project.description@'
        unit:
            fields-to-escape: ''
        version: '@project.version@'
eureka:
    client:
        enabled: ${SOLDIER_EUREKA_CLIENT_ENABLED}
        initial-instance-info-replication-interval-seconds: 120
        instance-info-replication-interval-seconds: 120
        serviceUrl:
            defaultZone: http://${SOLDIER_EUREKA_HOST}:${SOLDIER_EUREKA_PORT}/eureka
            registerWithEureka: true
    instance:
        prefer-ip-address: true
info:
    app:
        description: '@project.description@'
        encoding: '@project.build.sourceEncoding@'
        java:
            version: '@java.version@'
        name: '@project.name@'
        version: '@project.version@'
logging:
    level:
        org:
            hibernate:
                SQL: ${SOLDIER_LOGGING_LEVEL}
                type:
                    descriptor:
                        sql:
                            BasicBinder: ${SOLDIER_LOGGING_LEVEL}
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    #health:
        #mongo:
            #enabled: true
server:
    port: ${SOLDIER_SERVER_PORT}
spring:
    cloud:
        discovery:
            enabled: true
        loadbalancer:
            ribbon:
                enabled: false
        service-registry:
            auto-registration:
                enabled: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: $()Ld!3r
        url: jdbc:mysql://${SOLDIER_DATABASE_HOST}:${SOLDIER_DATABASE_PORT}/emp_soldier_db?logger=com.mysql.cj.log.StandardLogger
        username: emp_soldier_manager
    jpa:
        hibernate:
            ddl-auto: none
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    time_zone: UTC
                show_sql: true
                use_sql_comments: true
    sleuth:
        sampler:
            percentage: 1.0
        web:
            skipPattern: (^cleanup.*|.+favicon.*)
    zipkin:
        baseUrl: http://${SOLDIER_ZIPKIN_HOST}:${SOLDIER_ZIPKIN_PORT}
        enabled: ${SOLDIER_ZIPKIN_CLIENT_ENABLED}
springdoc:
    swagger-ui:
        enabled: ${SOLDIER_SWAGGER_ENABLED}
